version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: plucas/battlefun-io
    ports:
    - 8000:8000
    stop_signal: SIGINT

  frontend:
    build: frontend/
    image: plucas/battlefun-io-frontend
    ports:
    - 3000:3000

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - 2181:2181

  kafka-broker:
    image: wurstmeister/kafka:2.12-2.0.1
    ports:
    - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_CREATE_TOPICS: "to-statefun:1:1,from-statefun:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
    - zookeeper
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  master:
    build: statefun/
    expose:
    - "6123"
    ports:
    - 8081:8081
    environment:
    - ROLE=master
    - MASTER_HOST=master

  worker:
    build: statefun/
    expose:
    - "6121"
    - "6122"
    depends_on:
    - master
    - kafka-broker
    links:
    - master:master
    - kafka-broker:kafka-broker
    environment:
    - ROLE=worker
    - MASTER_HOST=master
