[package]
name = "battleship_gateway"
version = "0.1.0"
authors = ["Patrick Lucas <me@patricklucas.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
